name: Main

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2

      - name: Install dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: --prefer-dist

      - name: Run checks
        run: |
          composer cs
          composer test
